
  - name: Install chrony package
    package:
      name: chrony
      state: present

  - name: Start and enable chronyd service
    service:
      name: chronyd
      state: started
      enabled: yes

  - name: Synchronize time immediately using chronyc
    command: chronyc makestep
    ignore_errors: yes

