---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Download containerd package
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.6.33/containerd-1.6.33-linux-amd64.tar.gz
    dest: /tmp/containerd-1.6.33-linux-amd64.tar.gz

- name: Create directory for extraction
  file:
    path: /tmp/containerd-1.6.33
    state: directory

- name: Extract containerd package
  unarchive:
    src: /tmp/containerd-1.6.33-linux-amd64.tar.gz
    dest: /tmp/containerd-1.6.33
    remote_src: yes

- name: List extracted files
  command: ls -l /tmp/containerd-1.6.33
  register: extracted_files

- debug:
    var: extracted_files.stdout_lines

- name: Ensure containerd is installed
  package:
    name: containerd
    state: present

- name: Create containerd configuration
  command: containerd config default
  register: containerd_config

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Write containerd configuration
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Restart containerd
  service:
    name: containerd
    state: restarted

- name: Ensure containerd is started and enabled at boot
  service:
    name: containerd
    enabled: yes
    state: started

- name: Reload modules
  command: modprobe {{ item }}
  with_items:
    - overlay
    - br_netfilter

- name: Apply sysctl params
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { key: 'net.ipv4.ip_forward', value: 1 }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }

