    - name: Check if kubeconfig file exists
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present

    - name: Add Helm repository for NFS Subdir External Provisioner
      command: "helm repo add nfs-subdir-external-provisioner {{ helm_repo_url }}"
      args:
        creates: /etc/helm/repositories.yaml

    - name: Uninstall existing NFS Subdir External Provisioner (if any)
      command: >
        helm uninstall nfs-subdir-external-provisioner
      ignore_errors: true  # Ignore if the release does not exist
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Install NFS Subdir External Provisioner using Helm
      command: >
        helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        --set nfs.server={{ nfs_ip }}
        --set nfs.path={{ nfs_path }}
        --set storageClass.onDelete={{ storage_class_delete_behavior | lower }}
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        chdir: /tmp

    - name: Check storage class status
      command: "kubectl get storageclass {{ storage_class_name }}"
      register: storageclass_output
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Display storage class status
      debug:
        msg: "{{ storageclass_output.stdout }}"
