---
- name: Generate kubeadm join command for Master node
  hosts: k8s_node
  become: yes
  tasks:
    - name: enabling kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
    - name: config image
      command:
        cmd: "kubeadm config images pull"

    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: k8s_initialized

    - name: init master
      shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
      when: not k8s_initialized.stat.exists

    - name: Check if config file exists
      stat:
        path: "{{ ansible_user_dir }}/.kube/config"
      register: config_file_stat

    - name: Create .kube folder in home directory
      shell: mkdir -p /home/ansible-user/.kube
      args:
        executable: /bin/bash
      become: yes
      become_user: ansible-user
      when: not k8s_initialized.stat.exists

    - name: copy kubeconfig
      shell: sudo cp -i /etc/kubernetes/admin.conf /home/ansible-user/.kube/config
      args:
        executable: /bin/bash
      become: yes
      become_user: ansible-user
      when: not k8s_initialized.stat.exists

    - name: Check kubeconfig file ownership
      stat:
        path: "/home/ansible-user/.kube/config"
      register: kubeconfig_stat

    - name: Change ownership and permissions of config file
      ansible.builtin.command:
        cmd: "chown ansible-user:ansible-user /home/ansible-user/.kube/config && chmod 644 /home/ansible-user/.kube/config"
      become: yes
      when: kubeconfig_stat.stat.exists and kubeconfig_stat.stat.pw_name != 'ansible-user'

    - name: Import Cilium Networking role
      import_role:
        name: cilium

