---
- name: generate kubeadm join command for k8s nodes
  hosts: "{{ hostlist }}"
  become: yes
  tasks:
    - name: enabling kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
    - name: config image
      command:
        cmd: "kubeadm config images pull"
    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: k8s_initialized

    - name: init master
      shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
      when: not k8s_initialized.stat.exists

    - name: config master to work
      shell: mkdir -p $HOME/.kube
      args:
        executable: /bin/bash
      become: yes
      become_user: ansible-user
      when: not k8s_initialized.stat.exists

    - name: copy kubeconfig
      shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      args:
        executable: /bin/bash
      become: yes
      become_user: ansible-user

    - name: change ownership of config file
      shell: sudo chown ansible-user:ansible-user $HOME/.kube/config
      args:
        executable: /bin/bash
      become: yes
      become_user: root
