---
- name: Generate kubeadm join command for Master node
  hosts: k8s_node
  become: yes
  tasks:
    - name: enabling kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: config image
      command:
        cmd: "kubeadm config images pull"

    - name: Check if Kubernetes is already initialized
      stat:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
      register: k8s_initialized

    - name: init master
      shell: "kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
      when: not k8s_initialized.stat.exists

    - name: Check if config file exists
      stat:
        path: "{{ ansible_user_dir }}/.kube/config"
      register: config_file_stat

    - name: Debug k8s_initialized existence
      ansible.builtin.debug:
        msg: "k8s_initialized exists: {{ k8s_initialized.stat.exists }}"

    - name: Create .kube folder in home directory
      ansible.builtin.file:
        path: /home/ansible-user/.kube
        state: directory
        owner: ansible-user
        group: ansible-user
        mode: "0755"
      when: not k8s_initialized.stat.exists

    - name: Copy kubeconfig
      ansible.builtin.command:
        cmd: sudo cp -i /etc/kubernetes/admin.conf /home/ansible-user/.kube/config
      become_user: ansible-user
      when: not k8s_initialized.stat.exists

    - name: Check ownership and permissions of config file
      ansible.builtin.stat:
        path: /home/ansible-user/.kube/config
      register: kubeconfig_stat

    - name: Change ownership and permissions of config file on Ubuntu
      ansible.builtin.file:
        path: /home/ansible-user/.kube/config
        owner: ansible-user
        group: ansible-user
        mode: "0644"
      when: kubeconfig_stat.stat.exists and kubeconfig_stat.stat.pw_name != 'ansible-user'

    - name: Import Cilium Networking role
      import_role:
        name: cilium

