---
- name: Join Kubernetes Worker Node
  hosts: node
  become: yes
  tasks:
    - name: Join the worker node to the Kubernetes cluster
      command: "{{ join_command }}"
      environment:
        KUBECONFIG: /etc/kubernetes/kubelet.conf
      when: join_command is defined

    - name: Restart kubelet after joining the cluster
      systemd:
        name: kubelet
        state: restarted
