---
- name: Prepare nodes for running kubernetes
  hosts: controlplane
  become: yes
  tasks:
    - name: Import Kubernetes role
      import_role:
        name: kubernetes_role

    - name: Import Helm role
      import_role:
        name: helm
