---
- hosts: master[0]
  name: generate kubeadm join command for k8s nodes
  become: yes
  tasks:
    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Add node join command
      add_host:
        name: "dynamic_vars_holder"
        node_join_command: "{{ join_command.stdout }} --v=7"

- hosts: node
  name: generate kubeadm join command for k8s nodes
  become: yes
  tasks:
    - stat:
        path: "{{k8s_config_dir}}/kubelet.conf"
      register: kubelet.conf
    - stat:
        path: "sys/fs/chroup/cgroup.controllers"
      register: cgv2_controllers

    - name: Init node
      command: "{{ hostvars['dynamic_vars_holder']['node_join_command] }} --ignore-preflight-errors=FileContent--proc-sys-net-bridge-bridge-nf-call-iptables"
      when: not kubelet_conf.stat.exists
