---
- name: Synchronize time on all servers
  hosts: master
  become: yes

  tasks:
    - name: sync time across all masters
      import_role:
        name: time-sync

~
~
~
~
~
~
~
~
