---
- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_initialized

- name: Generate kubeadm configuration file
  template:
    src: roles/init-master/templates/config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    
- name: Initialize the Kubernetes control plane
  shell: "kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=NumCPU,Mem"
  args:
    executable: /bin/bash
  when: not k8s_initialized.stat.exists

- name: Check if /etc/kubernetes directory exists
  stat:
    path: /etc/kubernetes
  register: kubernetes_dir

- name: Print status message based on directory existence
  debug:
    msg: "/etc/kubernetes folder {{ 'exists' if kubernetes_dir.stat.exists else 'does not exist' }}."

- name: Check if Kubernetes is already initialized (kube-apiserver)
  stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: k8s_apiserver_initialized
