- name: Enabling kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Check if kubeadm config images are pulled
  command: "kubeadm config images list"
  register: kubeadm_images
  changed_when: false # Mark this task as not changed if the command output is as expected

- name: Pull kubeadm config images if not already pulled
  command: "kubeadm config images pull"
  when: kubeadm_images.stdout.find('image1') == -1

- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_initialized

- name: Initialize Kubernetes master node
  shell: 'kubeadm init --control-plane-endpoint "${{ LOAD_BALANCER_IP }}:{{ LOAD_BALANCER_PORT }}"--upload-certs'
  when: not k8s_initialized.stat.exists

- name: Check if /etc/kubernetes directory exists
  stat:
    path: /etc/kubernetes
  register: kubernetes_dir

- name: Print status message based on directory existence
  debug:
    msg: "/etc/kubernetes folder {{ 'exists' if kubernetes_dir.stat.exists else 'does not exist' }}."

- name: Check if Kubernetes is already initialized (kube-apiserver)
  stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: k8s_apiserver_initialized

- name: Create .kube folder for ansible-user
  become: yes
  file:
    path: "/home/ansible-user/.kube"
    state: directory
    owner: ansible-user
    group: ansible-user
    mode: "0755"
  when: not k8s_initialized.stat.exists

- name: Copy admin.conf to .kube folder for ansible-user
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible-user/.kube/config
    owner: ansible-user
    group: ansible-user
    mode: "0644"
    remote_src: yes
  when: not k8s_initialized.stat.exists

- name: Create .kube folder for root
  file:
    path: "/root/.kube"
    state: directory
    owner: "root"
    mode: "0755"

- name: Copy admin.conf to .kube folder for root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: "root"
    mode: "0644"
    remote_src: yes

- name: Copy admin.conf
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/admin.conf
    remote_src: yes

- name: Change permissions of admin.conf to ansible-user readable
  file:
    path: /etc/kubernetes/admin.conf
    owner: ansible-user
    group: ansible-user
    mode: "0644"

