- name: Save modified ConfigMap to temporary file
  copy:
    content: "{{ modified_configmap.stdout }}"
    dest: /tmp/kube-proxy-modified.yaml

- name: View and validate changes (simulate `kubectl diff`)
  command: kubectl diff -f /tmp/kube-proxy-modified.yaml -n kube-system
  register: diff_output
  ignore_errors: yes

- name: Display diff output
  debug:
    msg: "{{ diff_output.stdout }}"

- name: Apply changes if differences exist
  command: kubectl apply -f /tmp/kube-proxy-modified.yaml -n kube-system
  when: diff_output.rc == 1
  ignore_errors: yes

- name: Display message if no changes are needed or if an error occurred
  debug:
    msg: "No changes needed or an error occurred."
  when: diff_output.rc != 1
