- name: Get current kube-proxy ConfigMap
  command: kubectl get configmap kube-proxy -n kube-system -o yaml
  register: kube_proxy_configmap

- name: Prepare modified ConfigMap content
  set_fact:
    modified_configmap: "{{ kube_proxy_configmap.stdout | replace('strictARP: false', 'strictARP: true') }}"

- name: Save modified ConfigMap to temporary file
  copy:
    content: "{{ modified_configmap }}"
    dest: /tmp/kube-proxy-modified.yaml

- name: View and validate changes (simulate `kubectl diff`)
  command: kubectl diff -f /tmp/kube-proxy-modified.yaml -n kube-system
  register: diff_output
  ignore_errors: yes

- name: Display diff output
  debug:
    msg: "{{ diff_output.stdout }}"

- name: Apply changes if differences exist
  command: kubectl apply -f /tmp/kube-proxy-modified.yaml -n kube-system
  when: diff_output.rc == 1
  ignore_errors: yes

- name: Display message if no changes are needed
  debug:
    msg: "No changes needed or an error occurred."
  when: diff_output.rc != 1
