---
# roles/kubernetes/tasks/main.yml

- name: Set hostname
  hostname:
    name: "{{ ansible_hostname }}"

- name: Disable Swap
  shell: "sudo swapoff -a && sudo sed -i '/swap/d' /etc/fstab"

- name: Ensure /etc/modules-load.d/containerd.conf exists
  ansible.builtin.file:
    path: /etc/modules-load.d/containerd.conf
    state: touch

- name: Load kernel modules
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Load kernel modules
  command: "{{ item }}"
  loop:
    - "sudo modprobe overlay"
    - "sudo modprobe br_netfilter"

- name: Ensure sysctl configuration file exists
  ansible.builtin.file:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    state: touch

- name: Configure sysctl for Kubernetes
  blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl changes
  command: "sudo sysctl --system"

- name: Update package cache
  apt:
    update_cache: yes

- name: Update package cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg"

- name: Add Kubernetes apt key
  shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[1] }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"

- name: Add Kubernetes repository
  lineinfile:
    path: "/etc/apt/sources.list.d/kubernetes.list"
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[1] }}/deb/ /"

- name: Update package cache after adding repository
  apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "kubeadm={{ kubernetes_version }}"
    - "kubelet={{ kubernetes_version }}"
    - "kubectl={{ kubernetes_version }}"

- name: Hold Kubernetes packages
  apt_mark:
    name: "{{ item }}"
    state: hold
  loop:
    - "kubeadm"
    - "kubelet"
    - "kubectl"
