---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install NFS packages
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Create NFS export directory
  file:
    path: "{{ nfs_export_dir }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "0775"

- name: Set group read-write-execute permissions and setgid on NFS directory
  file:
    path: "{{ nfs_export_dir }}"
    mode: "2775"
    recurse: yes

- name: Apply NFS export configuration from template
  template:
    src: nfs_exports.j2
    dest: /etc/exports

- name: Export NFS shares
  command: exportfs -av
  notify: Restart NFS server

- name: Ensure NFS server is enabled and started
  systemd:
    name: nfs-kernel-server
    enabled: yes
    state: started

- name: Verify NFS exports
  command: /sbin/showmount -e localhost
  register: showmount_output

- debug:
    msg: "{{ showmount_output.stdout }}"

# Optional task: Add firewall rules if needed to allow NFS traffic
- name: Allow NFS traffic in firewall
  ufw:
    rule: allow
    proto: tcp
    from_ip: "{{ kubernetes_node_ip }}"  # Replace with your K8s nodes' IP range
    port: nfs

# Example handler to restart NFS server when exports are modified
- name: Restart NFS server
  systemd:
    name: nfs-kernel-server
    state: restarted
    enabled: yes
