---
- name: Create Argo CD namespace
  shell: kubectl create namespace {{ argo_namespace }}
  ignore_errors: yes  # Ignore if the namespace already exists
  environment:
    KUBECONFIG: /home/ansible-user/.kube/config
  when: inventory_hostname == 'master1'

- name: Apply Argo CD installation manifest
  shell: kubectl apply -n {{ argo_namespace }} -f {{ argo_manifest_url }}
  environment:
    KUBECONFIG: /home/ansible-user/.kube/config
  when: inventory_hostname == 'master1'
