---
- name: Add Cilium Helm repository
  ansible.builtin.shell: "helm repo add cilium https://helm.cilium.io/"

- name: Install Cilium using Helm
  ansible.builtin.shell: "helm install cilium cilium/cilium --version 1.15.4 --namespace kube-system"
