
- name: Fetch and set ownership/permissions of kube config file
  hosts: control-node
  tasks:
    - name: Fetch kube config file from remote server to Ansible control node
      ansible.builtin.fetch:
        src: /home/ansible-user/.kube/config
        dest: /home/ansible-user/.kube/config
        flat: yes

    - name: Set ownership and permissions of fetched config file on Ansible control node
      ansible.builtin.file:
        path: /home/ansible-user/.kube/config
        owner: ansible-user
        group: ansible-user
        mode: "0644"
        state: file
