# Set KUBECONFIG to use the correct kubeconfig file
- name: Set KUBECONFIG
  set_fact:
    kubeconfig_path: "/home/ansible-user/.kube/config"  # Adjust the path as necessary

# Ensure that kubectl is installed
- name: Ensure that kubectl is installed
  command: "which kubectl"
  register: kubectl_check
  changed_when: False
  failed_when: kubectl_check.rc != 0

# Apply the EBS CSI Driver using kustomize from the GitHub repository
- name: Apply the EBS CSI Driver using kustomize from the GitHub repository
  command: "kubectl apply -k 'github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master'"
  register: kubectl_apply_output
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ignore_errors: true  # Ignore errors for checking success

# Check if EBS CSI driver was applied successfully
- name: Check if EBS CSI driver was applied successfully
  command: "kubectl get pods -n kube-system -l app=ebs-csi-controller"
  register: ebs_driver_check
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  until: ebs_driver_check.rc == 0
  retries: 5
  delay: 30

# Debug EBS CSI driver installation result
- name: Debug EBS CSI driver installation result
  debug:
    msg: "{{ kubectl_apply_output.stdout }}"

# Check if StorageClass already exists
- name: Check if StorageClass gp2 exists
  command: "kubectl get storageclass gp2"
  register: storageclass_check
  failed_when: storageclass_check.rc not in [0, 1]
  changed_when: False
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

# Create StorageClass if it does not exist
- name: Create StorageClass if it does not exist
  template:
    src: "/home/ansible-user/ansible-playbook-k8s-installation/roles/ebs_csi_driver/templates/storageclass.yaml.j2"
    dest: /tmp/storageclass.yaml
  when: storageclass_check.rc == 1

# Apply StorageClass if it does not exist
- name: Apply StorageClass if it does not exist
  command: "kubectl apply -f /tmp/storageclass.yaml"
  when: storageclass_check.rc == 1
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

# Check if PersistentVolumeClaim already exists
- name: Check if PersistentVolumeClaim ebs-pvc exists
  command: "kubectl get pvc ebs-pvc"
  register: pvc_check
  failed_when: pvc_check.rc not in [0, 1]
  changed_when: False
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

# Create PersistentVolumeClaim if it does not exist
- name: Create PersistentVolumeClaim if it does not exist
  template:
    src: "/home/ansible-user/ansible-playbook-k8s-installation/roles/ebs_csi_driver/templates/persistentvolumeclaim.yaml.j2"
    dest: /tmp/persistentvolumeclaim.yaml
  when: pvc_check.rc == 1

# Apply PersistentVolumeClaim if it does not exist
- name: Apply PersistentVolumeClaim if it does not exist
  command: "kubectl apply -f /tmp/persistentvolumeclaim.yaml"
  when: pvc_check.rc == 1
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

# Remove the KUBECONFIG variable (optional)
- name: Remove KUBECONFIG variable
  set_fact:
    kubeconfig_path: ""
