
- name: Create .kube directory
  file:
    path: /home/ansible-user/.kube
    state: directory
    owner: ansible-user
    group: ansible-user
    mode: '0755'

- name: Check if admin.conf already exists locally
  stat:
      path: /tmp/admin.conf  # Path where you want to store admin.conf locally
  register: admin_conf_stat

- name: Fetch admin.conf from remote node if not already fetched
  delegate_to: control-plane
  become: yes
  fetch:
    remote_src: yes
    src: /etc/kubernetes/admin.conf  # Remote file path
    dest: /tmp/admin.conf  # Local destination path
    flat: yes  # Ensures the file is saved without the directory structure
  when: not admin_conf_stat.stat.exists

- name: Fetch admin.conf from remote node to local machine
  ansible.builtin.fetch:
    src: /tmp/admin.conf
    dest: /home/ansible-user/.kube/config
    flat: yes
  when: admin_conf_stat.stat.exists


- name: Clean up temporary admin.conf on remote node
  ansible.builtin.file:
     path: /tmp/admin.conf
     state: absent
  when: admin_conf_stat.stat.exists

- name: Set ownership and permissions of fetched config file on Ansible control node
  file:
    path: /home/ansible-user/.kube/config
    owner: ansible-user
    group: ansible-user
    mode: "0644"
    state: file
